theme: jekyll-theme-minimal
title: Class and Race Online Seminar Series  (CROSS)
description: CROSS is an online series that seeks to spotlight research that evaluates the intersection of class and race within the study of politics
logo: /raceclass.png
